project_id = "ydvnkqqtyvalvxcjhvbs"

[functions.keep-alive]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.update-user-password]
verify_jwt = true

[functions.update-user-email]
verify_jwt = true
